### ISSUE TITLE
Why? (real question)

### ISSUE THREAD

**Issue by str** [CryptoLions/SimpleAssets#1]
I don’t understand what the buzz is about with “non-fungible tokens” . It’s just yet another multi-index table like any others. I understand the “wow” for people who’ve only seen bitcoin where their blockchain was not made for a general purpose use. As you describe in your video, EOSWizards / CrytpoWizards already had that. It’s just another table.

What am I missing?

**Comment by rskaskiw** [comment]
Thanks for the comment.

Yes, an application, say, a game can implement its own internal assets.  Most do.  But prior to blockchain, anybody with a server could also implement a centralized ledger and invite the world to participate in a new form of money.  Some did-- see eGold, Liberty Reserve.

NFTs provide:

1. Depending how the contract is deployed, asset ownership can exist outside the control of the asset author, so it rearranges the trust relationship between players and games, or users and asset authors.

2. Ready integration with asset markets.  So the economics of an asset can live outside the game.

3. Standardization and true ownership may open the door the different games/applications sharing the same items, or importing the items from a different game.

4. Lastly, if nothing else, it just saves developers a ton of work to have a ready, working, tested model for NFTs, which have worked through all the subtleties and edge cases.
